--liquibase formatted sql

--changeset tadas.martinkus:201807111900
CREATE TABLE TODO_ITEM (
  ID          BIGINT NOT NULL,
  CREATED     TIMESTAMP,
  CONTENT     VARCHAR(255),
  ARCHIVED    BOOLEAN DEFAULT FALSE NOT NULL
);

--changeset tadas.martinkus:201807131738
CREATE SEQUENCE TODO_ITEM_ID